export type FeedUnit = "ml" | "g";
export type FeedPhase = "veg" | "flower" | "flush";

export type FeedWeek = {
  id: string;
  label: string;
  phase: FeedPhase;
  ec?: string;
  ph?: string;
};

export type FeedComment = {
  tone: "plus" | "moins" | "note";
  text: string;
};

export type FeedProduct = {
  id: string;
  name: string;
  role: string;
  unit: FeedUnit;
  npk?: string;
  about: string;
  mixTip?: string;
  comments: FeedComment[];
  /** Dose per litre, aligned with program.weeks */
  doses: number[];
};

export type FeedProgram = {
  id: string;
  brand: string;
  name: string;
  medium: string;
  summary: string;
  mixOrder: string;
  source: string;
  weeks: FeedWeek[];
  products: FeedProduct[];
};

const VEG2_FLOWER8_FLUSH: FeedWeek[] = [
  { id: "g1", label: "Veg 1", phase: "veg" },
  { id: "g2", label: "Veg 2", phase: "veg" },
  { id: "f1", label: "Flo 1", phase: "flower" },
  { id: "f2", label: "Flo 2", phase: "flower" },
  { id: "f3", label: "Flo 3", phase: "flower" },
  { id: "f4", label: "Flo 4", phase: "flower" },
  { id: "f5", label: "Flo 5", phase: "flower" },
  { id: "f6", label: "Flo 6", phase: "flower" },
  { id: "f7", label: "Flo 7", phase: "flower" },
  { id: "f8", label: "Flo 8", phase: "flower" },
  { id: "fl", label: "Flush", phase: "flush" },
];

export const CHART_COLORS = [
  "var(--color-primary)",
  "var(--color-ok)",
  "var(--color-warn)",
  "var(--color-fg)",
  "var(--color-muted)",
  "var(--color-danger)",
  "var(--color-subtle)",
  "var(--color-primary)",
];

export const PROGRAMS: FeedProgram[] = [
  {
    id: "biobizz-lightmix",
    brand: "BioBizz",
    name: "Light-Mix / Coco-Mix",
    medium: "terreau léger · coco",
    summary:
      "Schéma organique 2024–2025. Light-Mix et Coco-Mix sont peu chargés : tu nourris dès la veg. Doses en ml/L, à chaque arrosage.",
    mixOrder: "Secoue chaque bouteille. Dilue un produit après l'autre, mélange, pH 6,2–6,5.",
    source: "Tableau BioBizz Light-Mix / Coco-Mix (ml/L)",
    weeks: VEG2_FLOWER8_FLUSH.map((w, i) => ({
      ...w,
      ph: "6.2–6.5",
      ec: i === 10 ? "eau" : i < 2 ? "0.8–1.2" : i < 6 ? "1.2–1.6" : "1.4–1.8",
    })),
    products: [
      {
        id: "bb-root",
        name: "Root·Juice",
        role: "Racines",
        unit: "ml",
        about: "Stimulateur racinaire algues + humiques. Surtout plantule et bouture.",
        comments: [
          { tone: "plus", text: "Les boutures repartent plus vite après un stress de rempotage." },
          { tone: "note", text: "Inutile de le trainer toute la flo — la fenêtre utile, c'est le début." },
        ],
        doses: [4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      },
      {
        id: "bb-grow",
        name: "Bio·Grow",
        role: "Base veg",
        unit: "ml",
        npk: "4-3-6",
        about: "Base organique de croissance. On le garde bas en flo pour l'azote de relais.",
        comments: [
          { tone: "plus", text: "Odeur de mélasse, substrat vivant — beaucoup restent pour ça." },
          { tone: "moins", text: "En All-Mix, la dose Light-Mix brûle. Ici on est sur Light-Mix : 2–4 ml/L." },
        ],
        doses: [0, 2, 2, 2, 3, 3, 4, 4, 4, 4, 0],
      },
      {
        id: "bb-bloom",
        name: "Bio·Bloom",
        role: "Base flo",
        unit: "ml",
        npk: "2-7-4",
        about: "PK organique de floraison. Monte progressivement, pic en mi-flo.",
        comments: [
          { tone: "plus", text: "Les têtes se densifient sans le « sel » d'un minéral agressif." },
          { tone: "note", text: "Lent à corriger : tu baisses une semaine avant de juger." },
        ],
        doses: [0, 0, 1, 2, 2, 3, 3, 4, 4, 4, 0],
      },
      {
        id: "bb-topmax",
        name: "Top·Max",
        role: "Booster flo",
        unit: "ml",
        about: "Humiques + floraison. Pic à 4 ml/L en deuxième moitié de flo.",
        comments: [
          { tone: "plus", text: "Souvent cité pour le nez et la résine en fin de run." },
          { tone: "moins", text: "Bouteille chère. Beaucoup le tiennent à 1 ml/L jusqu'à flo 5, puis montent." },
        ],
        doses: [0, 0, 1, 1, 1, 1, 4, 4, 4, 4, 0],
      },
      {
        id: "bb-heaven",
        name: "Bio·Heaven",
        role: "Acides aminés",
        unit: "ml",
        about: "Vitalité, reprise d'azote organique. Monte jusqu'à 5 ml/L en pic.",
        comments: [
          { tone: "plus", text: "Les plantes « tiennent » mieux un VPD un peu haut." },
          { tone: "moins", text: "Coût. Si le budget est serré, Grow + Bloom + Top·Max suffisent." },
        ],
        doses: [2, 2, 2, 2, 3, 4, 4, 5, 5, 5, 0],
      },
      {
        id: "bb-alg",
        name: "Alg·A·Mic",
        role: "Stress / algues",
        unit: "ml",
        about: "Algues. Utile en Light-Mix. Foliaire possible 1–3×/semaine jusqu'à flo 2.",
        comments: [
          { tone: "plus", text: "Bon filet après un étêtage ou une chaleur." },
          { tone: "note", text: "En All-Mix on s'en passe souvent. Ici, Light-Mix : on le garde." },
        ],
        doses: [0, 0, 1, 2, 2, 3, 3, 4, 4, 4, 0],
      },
      {
        id: "bb-acti",
        name: "Acti·Vera",
        role: "Aloe",
        unit: "ml",
        about: "Aloe vera. Immunité, absorption. Foliaire possible en veg.",
        comments: [{ tone: "note", text: "Discret. Ceux qui l'enlèvent ne voient pas toujours la différence." }],
        doses: [1, 1, 1, 1, 1, 1, 4, 4, 4, 4, 0],
      },
    ],
  },
  {
    id: "biobizz-allmix",
    brand: "BioBizz",
    name: "All-Mix",
    medium: "terreau pré-fertilisé",
    summary:
      "All-Mix est déjà chargé 2–4 semaines. Doses plus basses que Light-Mix, surtout Bio·Grow. Mêmes produits, autre rythme.",
    mixOrder: "Comme Light-Mix. Ne pas empiler All-Mix neuf + tableau Light-Mix.",
    source: "Tableau BioBizz All-Mix (ml/L)",
    weeks: VEG2_FLOWER8_FLUSH.map((w, i) => ({
      ...w,
      ph: "6.2–6.5",
      ec: i === 10 ? "eau" : "0.8–1.4",
    })),
    products: [
      {
        id: "bb2-root",
        name: "Root·Juice",
        role: "Racines",
        unit: "ml",
        about: "Même rôle. En All-Mix, optionnel si la motte est déjà dense.",
        comments: [{ tone: "note", text: "Beaucoup sautent Root·Juice en All-Mix et commencent Grow en veg 2." }],
        doses: [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      },
      {
        id: "bb2-grow",
        name: "Bio·Grow",
        role: "Base veg",
        unit: "ml",
        npk: "4-3-6",
        about: "1 ml/L en All-Mix — la terre parle déjà.",
        comments: [
          { tone: "moins", text: "Le piège n°1 : coller le tableau Light-Mix sur de l'All-Mix. Pointes brûlées." },
        ],
        doses: [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
      },
      {
        id: "bb2-bloom",
        name: "Bio·Bloom",
        role: "Base flo",
        unit: "ml",
        npk: "2-7-4",
        about: "Même rampe que Light-Mix, la terre se vide en flo.",
        comments: [{ tone: "plus", text: "Une fois la charge All-Mix fondue, Bloom reprend le relais sans à-coup." }],
        doses: [0, 0, 1, 2, 2, 3, 3, 4, 4, 4, 0],
      },
      {
        id: "bb2-topmax",
        name: "Top·Max",
        role: "Booster flo",
        unit: "ml",
        about: "Identique Light-Mix en flo avancée.",
        comments: [{ tone: "plus", text: "Le duo Bloom + Top·Max est le cœur du schéma All-Mix en flo." }],
        doses: [0, 0, 1, 1, 1, 1, 4, 4, 4, 4, 0],
      },
      {
        id: "bb2-heaven",
        name: "Bio·Heaven",
        role: "Acides aminés",
        unit: "ml",
        about: "Même rampe. Optionnel si le budget est juste.",
        comments: [{ tone: "note", text: "En All-Mix, Heaven est un confort, pas un socle." }],
        doses: [2, 2, 2, 2, 3, 4, 4, 5, 5, 5, 0],
      },
    ],
  },
  {
    id: "canna-coco",
    brand: "Canna",
    name: "Coco A + B",
    medium: "coco drain-to-waste",
    summary:
      "Une seule base A+B du début à la fin. Doses officielles converties en ml/L (tableau ml/10 L). A et B toujours égaux, jamais mélangés concentrés.",
    mixOrder: "Eau → A → mélanger → B → mélanger → additifs → pH 5.5–6.2. 10–20 % de runoff.",
    source: "CANNA Coco schedule (ml/10 L → ml/L)",
    weeks: [
      { id: "g1", label: "Racine", phase: "veg", ec: "1.1–1.5", ph: "5.8–6.2" },
      { id: "g2", label: "Veg I", phase: "veg", ec: "1.3–1.7", ph: "5.8–6.2" },
      { id: "g3", label: "Veg II", phase: "veg", ec: "1.5–1.9", ph: "5.8–6.2" },
      { id: "f1", label: "Flo I", phase: "flower", ec: "1.8–2.2", ph: "5.8–6.2" },
      { id: "f2", label: "Flo I+", phase: "flower", ec: "1.8–2.2", ph: "5.8–6.2" },
      { id: "f3", label: "PK", phase: "flower", ec: "2.0–2.4", ph: "5.8–6.2" },
      { id: "f4", label: "Flo III", phase: "flower", ec: "1.4–1.8", ph: "5.8–6.2" },
      { id: "f5", label: "Flo III+", phase: "flower", ec: "1.4–1.8", ph: "5.8–6.2" },
      { id: "f6", label: "Mûr", phase: "flower", ec: "1.4–1.8", ph: "5.8–6.2" },
      { id: "fl", label: "Flush", phase: "flush", ec: "0.4", ph: "5.8–6.2" },
    ],
    products: [
      {
        id: "cc-a",
        name: "Coco A",
        role: "Base",
        unit: "ml",
        about: "Calcium, nitrates. Toujours la même dose que B.",
        mixTip: "En premier dans l'eau.",
        comments: [
          { tone: "plus", text: "Le standard coco. Beaucoup ne changent plus une fois le geste acquis." },
          { tone: "note", text: "Eau osmosée : Calmag jusqu'à EC eau ~0.4 avant A+B." },
        ],
        doses: [2, 2.5, 3, 3.5, 3.5, 3.5, 2.5, 2.5, 2.5, 0],
      },
      {
        id: "cc-b",
        name: "Coco B",
        role: "Base",
        unit: "ml",
        about: "Phosphore, potassium, micros. Égal à A.",
        mixTip: "Après A, jamais dans le bouchon avec A.",
        comments: [{ tone: "moins", text: "Mélanger A et B purs = précipité blanc, calcium coincé." }],
        doses: [2, 2.5, 3, 3.5, 3.5, 3.5, 2.5, 2.5, 2.5, 0],
      },
      {
        id: "cc-rhizo",
        name: "Rhizotonic",
        role: "Racines",
        unit: "ml",
        about: "Algues + B1. Fort en racine (4 ml/L), puis on descend.",
        comments: [
          { tone: "plus", text: "Après un topping ou un rempotage, la plante se rassied plus vite." },
          { tone: "note", text: "On peut le couper en mi-flo. Ce n'est pas un engrais NPK." },
        ],
        doses: [4, 2, 2, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0],
      },
      {
        id: "cc-zym",
        name: "Cannazym",
        role: "Enzymes",
        unit: "ml",
        about: "Décompose les racines mortes. 2.5 ml/L, double si coco réutilisée.",
        comments: [{ tone: "plus", text: "Utile si tu recycles le coco. Sinon, confort plus que besoin." }],
        doses: [0, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 3.5, 3.5],
      },
      {
        id: "cc-boost",
        name: "Cannaboost",
        role: "Stim flo",
        unit: "ml",
        about: "Glucides / métabolisme. 2 ml/L, jusqu'à 4 en flo si la plante avale.",
        comments: [
          { tone: "plus", text: "Certains voient densité et terpènes. D'autres n'y voient qu'une facture." },
          { tone: "moins", text: "Le plus cher du rayon. A+B seuls font déjà 80 % du travail." },
        ],
        doses: [0, 0, 2, 3, 3, 3, 3, 3, 3, 0],
      },
      {
        id: "cc-pk",
        name: "PK 13/14",
        role: "Booster 1 semaine",
        unit: "ml",
        about: "Une semaine, 3–4 semaines avant récolte. 1.5 ml/L. Pas plus.",
        comments: [
          { tone: "moins", text: "Souvent skippable : A+B portent déjà du PK. Trop longtemps = lockout." },
          { tone: "note", text: "Une semaine. Le tableau n'est pas une invitation à le laisser 4 semaines." },
        ],
        doses: [0, 0, 0, 0, 0, 1.5, 0, 0, 0, 0],
      },
    ],
  },
  {
    id: "canna-terra",
    brand: "Canna",
    name: "Terra Vega / Flores",
    medium: "terreau",
    summary:
      "Deux bases : Vega en veg, Flores en flo. Moins fréquent que Coco, même famille d'additifs. pH plus haut.",
    mixOrder: "Eau → Vega ou Flores → additifs → pH 5.8–6.2. En terreau chargé, arrose souvent à l'eau claire un tour sur deux.",
    source: "CANNA Terra (ml/L, synthèse tableaux Vega/Flores)",
    weeks: VEG2_FLOWER8_FLUSH.map((w, i) => ({
      ...w,
      ph: "5.8–6.2",
      ec: i === 10 ? "eau" : i < 2 ? "1.1–1.6" : i === 5 ? "1.8–2.2" : "1.4–2.0",
    })),
    products: [
      {
        id: "ct-vega",
        name: "Terra Vega",
        role: "Base veg",
        unit: "ml",
        about: "Croissance en terre. On le coupe dès l'entrée en 12/12.",
        comments: [{ tone: "plus", text: "Simple : une bouteille en veg, une en flo. Moins d'erreurs A+B." }],
        doses: [2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      },
      {
        id: "ct-flores",
        name: "Terra Flores",
        role: "Base flo",
        unit: "ml",
        about: "Floraison terre. 3–4 ml/L selon la charge du terreau.",
        comments: [{ tone: "note", text: "Terreau « plus » (All-Mix style) : commence bas, 2 ml/L, et lis les pointes." }],
        doses: [0, 0, 3, 3.5, 4, 4, 3.5, 3, 2.5, 2, 0],
      },
      {
        id: "ct-rhizo",
        name: "Rhizotonic",
        role: "Racines",
        unit: "ml",
        about: "Comme en coco, surtout le premier mois.",
        comments: [{ tone: "plus", text: "Même bouteille que le schéma Coco — un seul additif à acheter deux fois." }],
        doses: [4, 2, 0.5, 0.5, 0, 0, 0, 0, 0, 0, 0],
      },
      {
        id: "ct-pk",
        name: "PK 13/14",
        role: "Booster 1 semaine",
        unit: "ml",
        about: "Une semaine en mi-flo.",
        comments: [{ tone: "moins", text: "En terre déjà riche, beaucoup s'en passent." }],
        doses: [0, 0, 0, 0, 0, 1.5, 0, 0, 0, 0, 0],
      },
      {
        id: "ct-boost",
        name: "Cannaboost",
        role: "Stim flo",
        unit: "ml",
        about: "Optionnel dès flo 1.",
        comments: [{ tone: "note", text: "Même débat qu'en coco : luxe vs A/B (ici Vega/Flores) seuls." }],
        doses: [0, 0, 2, 2, 3, 3, 3, 3, 2, 2, 0],
      },
    ],
  },
  {
    id: "an-sensi",
    brand: "Advanced Nutrients",
    name: "pH Perfect Sensi",
    medium: "coco · hydro · terre",
    summary:
      "Base A+B qui tamponne le pH. Veg : Sensi Grow A/B en rampe 1→4 ml/L. Flo : Sensi Bloom A/B à 4 ml/L. Les boosters sont optionnels — 4 ml/L de base est déjà chaud pour beaucoup.",
    mixOrder: "Eau → Grow ou Bloom A → B → micros/boosters un par un. Ne pas stacker toute la gamme au premier run.",
    source: "AN pH Perfect Sensi Global (ml/L)",
    weeks: VEG2_FLOWER8_FLUSH.map((w, i) => ({
      ...w,
      ph: "auto ~5.5–6.3",
      ec: i === 10 ? "flush" : i < 2 ? "1.0–1.6" : "1.6–2.2",
    })),
    products: [
      {
        id: "an-ga",
        name: "Sensi Grow A",
        role: "Base veg",
        unit: "ml",
        about: "Rampe veg 1–4 ml/L. On arrête à l'entrée en 12/12.",
        comments: [{ tone: "plus", text: "Le pH Perfect sauve des débutants qui n'ont pas de stylo pH fiable." }],
        doses: [1, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      },
      {
        id: "an-gb",
        name: "Sensi Grow B",
        role: "Base veg",
        unit: "ml",
        about: "Égal à Grow A.",
        comments: [{ tone: "note", text: "Veg 1 = 1 ml/L. J'ai mis veg 2 à 4 ml/L (semaine 4 du tableau). Entre les deux, rampe 2 puis 3 si ta veg dure." }],
        doses: [1, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      },
      {
        id: "an-ba",
        name: "Sensi Bloom A",
        role: "Base flo",
        unit: "ml",
        about: "4 ml/L toute la flo selon le tableau officiel.",
        comments: [
          { tone: "moins", text: "4 ml/L A + 4 ml/L B, beaucoup voient du tip burn. Commence à 70 % (≈2.8) si tes LED sont fortes." },
        ],
        doses: [0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 0],
      },
      {
        id: "an-bb",
        name: "Sensi Bloom B",
        role: "Base flo",
        unit: "ml",
        about: "Égal à Bloom A.",
        comments: [{ tone: "note", text: "Si les pointes cramées : -25 % sur A et B, pas sur un seul." }],
        doses: [0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 0],
      },
      {
        id: "an-big",
        name: "Big Bud",
        role: "PK flo",
        unit: "ml",
        about: "Booster mi-flo, 2 ml/L semaines 2–4 de flo environ.",
        comments: [
          { tone: "plus", text: "Le booster dont on parle le plus — densité." },
          { tone: "moins", text: "Avec Bloom déjà à 4, Big Bud pousse l'EC. Surveille le runoff." },
        ],
        doses: [0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0],
      },
      {
        id: "an-over",
        name: "Overdrive",
        role: "Finisher",
        unit: "ml",
        about: "Fin de flo, 2 ml/L.",
        comments: [{ tone: "note", text: "Remplace Big Bud en fin, ne les stack pas." }],
        doses: [0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0],
      },
      {
        id: "an-candy",
        name: "Bud Candy",
        role: "Glucides / terpènes",
        unit: "ml",
        about: "2 ml/L en flo. Goût / sucres.",
        comments: [{ tone: "plus", text: "Ceux qui y croient parlent de nez. Ceux qui n'y croient pas parlent de prix." }],
        doses: [0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0],
      },
    ],
  },
  {
    id: "athena-blended",
    brand: "Athena",
    name: "Blended (liquide)",
    medium: "coco · laine · tourbe",
    summary:
      "Tableau métrique (ml/10 L → ml/L). Grow A+B en veg, Bloom A+B en flo, PK à partir de flo 3. EC élevé — c'est un schéma de salle, pas un 70 % débutant.",
    mixOrder: "Balance (pH up) si besoin → Bloom/Grow B → A → PK → CaMg → Cleanse. pH coco 5.8–6.2.",
    source: "Athena Blended metric v18 (ml/10 L)",
    weeks: [
      { id: "g1", label: "Veg 1", phase: "veg", ec: "2.1", ph: "5.8–6.2" },
      { id: "g2", label: "Veg 2–4", phase: "veg", ec: "2.1", ph: "5.8–6.2" },
      { id: "f1", label: "Flo 1–2", phase: "flower", ec: "2.3", ph: "5.8–6.2" },
      { id: "f3", label: "Flo 3", phase: "flower", ec: "2.5", ph: "5.8–6.2" },
      { id: "f4", label: "Flo 4", phase: "flower", ec: "2.6", ph: "5.8–6.2" },
      { id: "f5", label: "Flo 5", phase: "flower", ec: "2.4", ph: "5.8–6.2" },
      { id: "f6", label: "Flo 6", phase: "flower", ec: "2.3", ph: "5.8–6.2" },
      { id: "f7", label: "Flo 7", phase: "flower", ec: "1.7", ph: "5.8–6.2" },
      { id: "f8", label: "Flo 8–9", phase: "flower", ec: "1.5", ph: "6.0–6.4" },
      { id: "fl", label: "Flush", phase: "flush", ec: "<0.4", ph: "6.0–6.4" },
    ],
    products: [
      {
        id: "at-ga",
        name: "Grow A",
        role: "Base veg",
        unit: "ml",
        about: "2.9 ml/L en veg (29 ml/10 L).",
        comments: [{ tone: "plus", text: "Propre, répétible. C'est pour ça que les salles l'ont adopté." }],
        doses: [2.9, 2.9, 0, 0, 0, 0, 0, 0, 0, 0],
      },
      {
        id: "at-gb",
        name: "Grow B",
        role: "Base veg",
        unit: "ml",
        about: "Égal à Grow A.",
        mixTip: "B avant A, dit le tableau.",
        comments: [{ tone: "note", text: "Toujours B puis A chez Athena Blended." }],
        doses: [2.9, 2.9, 0, 0, 0, 0, 0, 0, 0, 0],
      },
      {
        id: "at-ba",
        name: "Bloom A",
        role: "Base flo",
        unit: "ml",
        about: "3.2 ml/L en début de flo, on redescend en fin.",
        comments: [{ tone: "moins", text: "EC 2.3–2.6 : trop pour une tente chaude et une première run. 70 % est légitime." }],
        doses: [0, 0, 3.2, 3.2, 3.2, 2.6, 2.4, 1.3, 0, 0],
      },
      {
        id: "at-bb2",
        name: "Bloom B",
        role: "Base flo",
        unit: "ml",
        about: "Égal à Bloom A.",
        comments: [{ tone: "note", text: "Si tu coupes A, tu coupes B d'autant." }],
        doses: [0, 0, 3.2, 3.2, 3.2, 2.6, 2.4, 1.3, 0, 0],
      },
      {
        id: "at-pk",
        name: "PK",
        role: "Booster",
        unit: "ml",
        about: "Rampe flo 3 → 7, puis on garde en fade.",
        comments: [{ tone: "plus", text: "Plus finement dosé que le PK 13/14 « une semaine et ciao »." }],
        doses: [0, 0, 0, 1.1, 1.6, 2.4, 2.6, 3.2, 3.2, 0],
      },
      {
        id: "at-camg",
        name: "CaMg",
        role: "Cal-mag",
        unit: "ml",
        about: "0.8–1.3 ml/L (8–13 ml/10 L) en coco / LED / eau douce.",
        comments: [{ tone: "plus", text: "En coco + LED, presque tout le monde le laisse coché." }],
        doses: [1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
      },
      {
        id: "at-clean",
        name: "Cleanse",
        role: "Ligne / sels",
        unit: "ml",
        about: "0.5–1.3 ml/L. Hypochlorite stabilisé — garder les lignes propres.",
        comments: [{ tone: "note", text: "Surtout utile en goutte-à-goutte. En arrosoir, optionnel." }],
        doses: [0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9],
      },
    ],
  },
  {
    id: "ta-coco",
    brand: "Terra Aquatica",
    name: "TriPart coco / hydro",
    medium: "coco · hydro",
    summary:
      "L'ancien Flora Series (GHE). Trois bouteilles toute la run, les ratios changent. Micro toujours en premier. Eau douce vs dure : bouteille Micro différente.",
    mixOrder: "Micro → Grow → Bloom, mélanger entre chaque. Jamais les concentrés ensemble.",
    source: "TA TriPart hydro/coco easy (ml/L)",
    weeks: [
      { id: "g1", label: "Racines", phase: "veg", ec: "0.3–0.6", ph: "5.5–6.2" },
      { id: "g2", label: "Plantule", phase: "veg", ec: "0.8–1.2", ph: "5.5–6.2" },
      { id: "g3", label: "Veg", phase: "veg", ec: "1.3–1.8", ph: "5.5–6.2" },
      { id: "f1", label: "Pré-flo", phase: "flower", ec: "1.8–2.0", ph: "5.8–6.2" },
      { id: "f2", label: "Flo", phase: "flower", ec: "1.4–2.2", ph: "5.8–6.2" },
      { id: "f3", label: "Flo+", phase: "flower", ec: "1.4–2.2", ph: "5.8–6.2" },
      { id: "ri", label: "Maturation", phase: "flower", ec: "1.4–2.6", ph: "5.8–6.2" },
      { id: "fl", label: "Flush", phase: "flush", ec: "—", ph: "6.0" },
    ],
    products: [
      {
        id: "ta-micro",
        name: "TriPart Micro",
        role: "Micros + Ca",
        unit: "ml",
        about: "Toujours en premier. Choisir Hard ou Soft water.",
        mixTip: "Premier dans l'eau.",
        comments: [
          { tone: "plus", text: "Une gamme, trois bouteilles, 20 ans de recette. Pas cher, prévisible." },
          { tone: "moins", text: "Micro hard dans une eau déjà dure = calcaire et lockout. Lis l'étiquette." },
        ],
        doses: [0.5, 1, 1.2, 2, 1.6, 1.6, 0, 0],
      },
      {
        id: "ta-grow",
        name: "TriPart Grow",
        role: "Azote veg",
        unit: "ml",
        npk: "N-forward",
        about: "Monte en veg, redescend fort en flo.",
        comments: [{ tone: "note", text: "Si tu laisses Grow à 2 ml/L en pleine flo, l'azote retarde la maturité." }],
        doses: [0.5, 1, 1.8, 2, 0.8, 0.8, 0, 0],
      },
      {
        id: "ta-bloom",
        name: "TriPart Bloom",
        role: "PK flo",
        unit: "ml",
        about: "Bas en veg, 2.4 ml/L en flo.",
        comments: [{ tone: "plus", text: "Le 3-part permet de sculpter : plus de Bloom, moins de Grow, sans changer de marque." }],
        doses: [0.5, 1, 0.6, 1.5, 2.4, 2.4, 0, 0],
      },
      {
        id: "ta-final",
        name: "FinalPart / Ripen",
        role: "Maturation",
        unit: "ml",
        about: "5 ml/L tout seul (ou presque) en dernière ligne, 1–2 semaines.",
        comments: [{ tone: "plus", text: "Force la plante à tirer sur ses réserves. Ne pas le laisser 4 semaines." }],
        doses: [0, 0, 0, 0, 0, 0, 5, 0],
      },
      {
        id: "ta-flash",
        name: "FlashClean",
        role: "Rinçage",
        unit: "ml",
        about: "2 ml/L en flush, parfois un lavage en cours de flo si sels.",
        comments: [{ tone: "note", text: "Mieux qu'un flush d'eau seule si le coco est chargé." }],
        doses: [0, 0, 0, 0, 0, 0, 2, 2],
      },
    ],
  },
  {
    id: "ta-soil",
    brand: "Terra Aquatica",
    name: "TriPart terreau",
    medium: "terreau",
    summary: "Même 3-part, doses plus basses. En terre, souvent un arrosage sur deux.",
    mixOrder: "Micro → Grow → Bloom. pH 6.0–6.5.",
    source: "TA TriPart soil easy (ml/L)",
    weeks: [
      { id: "g1", label: "Racines", phase: "veg", ec: "0.2–0.5", ph: "6.0–6.5" },
      { id: "g2", label: "Plantule", phase: "veg", ec: "0.6–1.0", ph: "6.0–6.5" },
      { id: "g3", label: "Veg", phase: "veg", ec: "1.1–1.6", ph: "6.0–6.5" },
      { id: "f1", label: "Pré-flo", phase: "flower", ec: "1.4–1.8", ph: "6.0–6.5" },
      { id: "f2", label: "Flo", phase: "flower", ec: "1.3–1.7", ph: "6.0–6.5" },
      { id: "ri", label: "Maturation", phase: "flower", ec: "1.3–2.0", ph: "6.0–6.5" },
      { id: "fl", label: "Flush", phase: "flush", ec: "—", ph: "6.2" },
    ],
    products: [
      {
        id: "tas-micro",
        name: "TriPart Micro",
        role: "Micros + Ca",
        unit: "ml",
        about: "Doses terre, plus douces.",
        comments: [{ tone: "plus", text: "En terreau déjà vivant, le 3-part se glisse sans tout remplacer." }],
        doses: [0.2, 0.6, 1, 1.5, 1.4, 0, 0],
      },
      {
        id: "tas-grow",
        name: "TriPart Grow",
        role: "Azote veg",
        unit: "ml",
        about: "1.5 ml/L en veg / pré-flo.",
        comments: [{ tone: "note", text: "Un arrosage sur deux si le terreau est pré-fertilisé." }],
        doses: [0.2, 0.6, 1.5, 1.5, 0.7, 0, 0],
      },
      {
        id: "tas-bloom",
        name: "TriPart Bloom",
        role: "PK flo",
        unit: "ml",
        about: "2.1 ml/L en flo terre.",
        comments: [{ tone: "plus", text: "Moins agressif que le tableau coco — la terre buffer." }],
        doses: [0.2, 0.6, 0.5, 1, 2.1, 0, 0],
      },
      {
        id: "tas-final",
        name: "FinalPart",
        role: "Maturation",
        unit: "ml",
        about: "4 ml/L en terre (5 en coco).",
        comments: [{ tone: "note", text: "Une à deux semaines, puis eau." }],
        doses: [0, 0, 0, 0, 0, 4, 0],
      },
    ],
  },
  {
    id: "plagron-terra",
    brand: "Plagron",
    name: "100% Terra Light-Mix",
    medium: "terreau Light-Mix",
    summary:
      "Doses officielles par 10 L, converties en ml/L. Vega 2 semaines, Bloom ensuite. Green Sensation est l'additif dont tout le monde parle.",
    mixOrder: "Base Terra → Power Roots / Pure Zym → Green Sensation. pH 6.0–6.5. Chaque arrosage.",
    source: "Plagron 100% Terra Light-Mix (ml/10 L)",
    weeks: [
      { id: "g1", label: "Veg 1", phase: "veg", ec: "1.0", ph: "6.0–6.5" },
      { id: "g2", label: "Veg 2", phase: "veg", ec: "1.6", ph: "6.0–6.5" },
      { id: "f1", label: "Flo 1", phase: "flower", ec: "1.6", ph: "6.0–6.5" },
      { id: "f2", label: "Flo 2", phase: "flower", ec: "1.6", ph: "6.0–6.5" },
      { id: "f3", label: "Flo 3", phase: "flower", ec: "1.6", ph: "6.0–6.5" },
      { id: "f4", label: "Flo 4", phase: "flower", ec: "1.8", ph: "6.0–6.5" },
      { id: "f5", label: "Flo 5", phase: "flower", ec: "1.9", ph: "6.0–6.5" },
      { id: "f6", label: "Flo 6", phase: "flower", ec: "2.0", ph: "6.0–6.5" },
      { id: "f7", label: "Flo 7", phase: "flower", ec: "2.0", ph: "6.0–6.5" },
      { id: "f8", label: "Flo 8", phase: "flower", ec: "2.0", ph: "6.0–6.5" },
      { id: "fl", label: "Récolte", phase: "flush", ec: "eau", ph: "6.0–6.5" },
    ],
    products: [
      {
        id: "pl-grow",
        name: "Terra Grow",
        role: "Base veg",
        unit: "ml",
        about: "2.5 puis 5 ml/L. Ensuite on passe à Bloom.",
        comments: [{ tone: "plus", text: "Schéma lisible : deux semaines de Grow, le reste en Bloom." }],
        doses: [2.5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      },
      {
        id: "pl-bloom",
        name: "Terra Bloom",
        role: "Base flo",
        unit: "ml",
        about: "4–5 ml/L selon la semaine (40–50 ml/10 L).",
        comments: [{ tone: "note", text: "En Growmix (plus chargé), tu sautes souvent Terra Grow et tu entres direct Bloom." }],
        doses: [0, 0, 5, 5, 5, 4, 4.5, 5, 5, 5, 0],
      },
      {
        id: "pl-roots",
        name: "Power Roots",
        role: "Racines",
        unit: "ml",
        about: "1 ml/L les 5 premières semaines.",
        comments: [{ tone: "plus", text: "Discret et régulier. Peu de gens s'en plaignent." }],
        doses: [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
      },
      {
        id: "pl-zym",
        name: "Pure Zym",
        role: "Enzymes",
        unit: "ml",
        about: "1 ml/L jusqu'en mi-flo.",
        comments: [{ tone: "note", text: "Confort de substrat plus que booster de têtes." }],
        doses: [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
      },
      {
        id: "pl-gs",
        name: "Green Sensation",
        role: "Booster flo",
        unit: "ml",
        about: "1 ml/L à partir de flo 4–5 (10 ml/10 L). Le plus commenté de la marque.",
        comments: [
          { tone: "plus", text: "Densité, brillance, « ça vaut la bouteille » — refrain fréquent." },
          { tone: "moins", text: "Prix au ml. Beaucoup le gardent et sautent Sugar Royal." },
        ],
        doses: [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0],
      },
      {
        id: "pl-sugar",
        name: "Sugar Royal",
        role: "Glucides",
        unit: "ml",
        about: "1 ml/L presque toute la run.",
        comments: [{ tone: "note", text: "Moins décisif que Green Sensation d'après la plupart des retours." }],
        doses: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
      },
    ],
  },
  {
    id: "ghf-hybrids",
    brand: "Green House Feeding",
    name: "Powder Hybrids",
    medium: "terre · coco · hydro",
    summary:
      "Poudre 15-7-22 pour hybrides 8–10 semaines de flo. Doses en g/L. Un seau, une cuillère, peu de bouteilles. PK+ en option dès mi-flo.",
    mixOrder: "Eau → poudre jusqu'à dissolution → Calcium si eau douce → pH. Foliaire = dose / 10.",
    source: "GHF Hybrids professional (g/L)",
    weeks: [
      { id: "g1", label: "Jeune", phase: "veg", ec: "0.8", ph: "5.8–6.2" },
      { id: "g2", label: "Veg", phase: "veg", ec: "1.0", ph: "5.8–6.2" },
      { id: "g3", label: "Veg+", phase: "veg", ec: "1.1", ph: "5.8–6.2" },
      { id: "f1", label: "Flo 1–2", phase: "flower", ec: "1.1", ph: "5.8–6.2" },
      { id: "f3", label: "Flo 3–4", phase: "flower", ec: "0.8", ph: "5.8–6.2" },
      { id: "f5", label: "Flo 5–6", phase: "flower", ec: "0.7", ph: "5.8–6.2" },
      { id: "f7", label: "Flo 7–8", phase: "flower", ec: "0.6", ph: "5.8–6.2" },
      { id: "fl", label: "Flush", phase: "flush", ec: "0", ph: "6.0" },
    ],
    products: [
      {
        id: "gh-hyb",
        name: "Hybrids",
        role: "Base poudre",
        unit: "g",
        npk: "15-7-22",
        about: "0.6–0.8 g/L selon la taille, on redescend en fin de flo.",
        comments: [
          { tone: "plus", text: "Un sac, 50 runs. Les voyageurs et les micro-tentes l'adorent." },
          { tone: "moins", text: "Sans CalMag en eau osmose, les carences Ca arrivent vite sous LED." },
        ],
        doses: [0.6, 0.7, 0.8, 0.8, 0.6, 0.5, 0.4, 0],
      },
      {
        id: "gh-pk",
        name: "Booster PK+",
        role: "PK poudre",
        unit: "g",
        about: "0.4–0.6 g/L à partir de flo 3.",
        comments: [{ tone: "plus", text: "Plus souple qu'un PK liquide « une semaine » : tu doses au gramme." }],
        doses: [0, 0, 0, 0, 0.4, 0.55, 0.5, 0],
      },
      {
        id: "gh-ca",
        name: "Calcium",
        role: "Cal-mag",
        unit: "g",
        about: "0.5–1 g/L si l'eau est douce. Avant la poudre de base.",
        comments: [{ tone: "note", text: "Inutile sur une eau déjà à 0.4+ d'EC calcaire." }],
        doses: [0.5, 0.75, 1, 1, 1, 1, 0.5, 0],
      },
    ],
  },
  {
    id: "hesi-coco",
    brand: "Hesi",
    name: "Coco",
    medium: "coco",
    summary:
      "TNT en veg, Hesi Coco en flo. Doses officielles en ml/10 L converties. PK 13/14 en rampe à partir de flo 4 — ne pas coller 1.5 ml/L trop tôt.",
    mixOrder: "Eau → TNT ou Coco → Root Complex → PowerZyme → PK → Boost. SuperVit : 1 goutte / 5 L. pH 5.8–6.2.",
    source: "Hesi Coco grow schedule (ml/10 L → ml/L)",
    weeks: VEG2_FLOWER8_FLUSH.map((w, i) => ({
      ...w,
      ph: "5.8–6.2",
      ec: i === 10 ? "eau" : i < 2 ? "1.0–1.4" : "1.4–2.0",
    })),
    products: [
      {
        id: "he-tnt",
        name: "TNT Complex",
        role: "Base veg",
        unit: "ml",
        npk: "3-2-3",
        about: "Base croissance, même en coco. 2.5 ml/L en veg 1, 5 ml/L ensuite. On le coupe au 12/12.",
        comments: [
          { tone: "plus", text: "Simple et pas cher. Une bouteille en veg, une en flo — le geste s'apprend vite." },
          { tone: "moins", text: "TNT à 5 ml/L sous LED forte : quelques-uns voient du claw. 70 % la première semaine de veg 2." },
        ],
        doses: [2.5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      },
      {
        id: "he-coco",
        name: "Hesi Coco",
        role: "Base flo",
        unit: "ml",
        npk: "3-4-5",
        about: "Base unique de floraison coco, 5 ml/L. Calmag déjà dans la formule.",
        comments: [
          { tone: "plus", text: "Pas d'A+B à rater. Le coco Hesi tient le Ca mieux qu'un Bloom générique." },
          { tone: "note", text: "Ce n'est pas un Terra Bloom versé dans du coco — c'est une formule à part." },
        ],
        doses: [0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 0],
      },
      {
        id: "he-root",
        name: "Root Complex",
        role: "Racines",
        unit: "ml",
        about: "2 ml/L (20 ml/10 L) en veg et première semaine de flo.",
        comments: [{ tone: "plus", text: "Après rempotage, beaucoup le gardent 3 semaines et le sentent aux racines blanches." }],
        doses: [2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0],
      },
      {
        id: "he-zym",
        name: "PowerZyme",
        role: "Enzymes",
        unit: "ml",
        about: "2 ml/L, 1–2 fois par semaine. Ici calé à chaque arrosage pour le calcul — tu peux le sauter un tour sur deux.",
        comments: [{ tone: "note", text: "Utile si tu réutilises le coco. En sac neuf, confort plus que besoin." }],
        doses: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0],
      },
      {
        id: "he-pk",
        name: "PK 13/14",
        role: "Booster flo",
        unit: "ml",
        about: "Rampe officielle : 0.25 → 0.5 → 0.75 → 1.5 ml/L à partir de flo 4. Doubler d'un coup brûle.",
        comments: [
          { tone: "moins", text: "Le piège Hesi n°1 : coller 1.5 ml/L dès flo 2. Lockout K, pointes brûlées." },
          { tone: "plus", text: "La rampe lente est le vrai schéma. Respectée, elle passe." },
        ],
        doses: [0, 0, 0, 0, 0, 0.25, 0.5, 0.75, 1.5, 1.5, 0],
      },
      {
        id: "he-boost",
        name: "Hesi Boost",
        role: "Stim flo",
        unit: "ml",
        about: "2 ml/L, plutôt 1×/semaine en entrée de flo puis mi-flo. Ici calé sur les semaines où le tableau le montre.",
        comments: [{ tone: "note", text: "Ce n'est pas un PK. Odeur / sucres. Beaucoup le sautent sans drame." }],
        doses: [0, 0, 2, 0, 0, 2, 2, 2, 0, 0, 0],
      },
      {
        id: "he-vit",
        name: "SuperVit",
        role: "Vitamines",
        unit: "ml",
        about: "1 goutte / 5 L. La valeur 0.01 ml/L est indicative pour le calculateur — compte les gouttes, pas la seringue.",
        mixTip: "1 goutte pour 5 litres, toute la run jusqu'au flush.",
        comments: [
          { tone: "plus", text: "Cul-de-sac de forum : une micro-bouteille, des années. Ceux qui y croient n'arrêtent plus." },
          { tone: "note", text: "Impossible à « surdoser » en ml dans ce tableau : reste sur les gouttes." },
        ],
        doses: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0],
      },
    ],
  },
  {
    id: "hesi-soil",
    brand: "Hesi",
    name: "Terre",
    medium: "terreau",
    summary:
      "TNT en veg, Floraison (Bloom Complex) en flo, Phosphor Plus à la place du PK 13/14. En terreau chargé, un arrosage sur deux.",
    mixOrder: "Eau → TNT ou Floraison → Root → PowerZyme → Phosphor Plus. pH 6.0–6.5. Terreau pré-fertilisé : 50–70 %.",
    source: "Hesi Soil schedule (ml/10 L → ml/L)",
    weeks: VEG2_FLOWER8_FLUSH.map((w, i) => ({
      ...w,
      ph: "6.0–6.5",
      ec: i === 10 ? "eau" : i < 2 ? "0.8–1.2" : "1.2–1.8",
    })),
    products: [
      {
        id: "hs-tnt",
        name: "TNT Complex",
        role: "Base veg",
        unit: "ml",
        about: "Même TNT qu'en coco. En All-Mix / terreau « plus », commence à 2.5 et reste-y.",
        comments: [{ tone: "moins", text: "TNT 5 ml/L sur un All-Mix neuf = pointes. Lis la charge du sac." }],
        doses: [2.5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      },
      {
        id: "hs-bloom",
        name: "Floraison",
        role: "Base flo",
        unit: "ml",
        about: "Bloom Complex terre, rampe 3 → 5 ml/L.",
        comments: [{ tone: "plus", text: "Moins agressif que le schéma coco. La terre buffer." }],
        doses: [0, 0, 3, 3, 3, 4, 4, 5, 5, 5, 0],
      },
      {
        id: "hs-root",
        name: "Root Complex",
        role: "Racines",
        unit: "ml",
        about: "5 ml/L (50 ml/10 L) en début, plus fort qu'en coco.",
        comments: [{ tone: "plus", text: "Les boutures en godet y répondent bien — un des usages les plus cités." }],
        doses: [5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0],
      },
      {
        id: "hs-phos",
        name: "Phosphor Plus",
        role: "Booster flo",
        unit: "ml",
        about: "2.5 ml/L à partir de flo 4. L'équivalent terre du PK 13/14.",
        comments: [{ tone: "note", text: "En terre déjà riche, beaucoup le tiennent à 1.5 ml/L. Le 2.5 est un plafond." }],
        doses: [0, 0, 0, 0, 0, 2.5, 2.5, 2.5, 2.5, 2.5, 0],
      },
      {
        id: "hs-zym",
        name: "PowerZyme",
        role: "Enzymes",
        unit: "ml",
        about: "2 ml/L, 1–2×/semaine.",
        comments: [{ tone: "note", text: "En terre vivante, optionnel. En terreau inerte, utile." }],
        doses: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0],
      },
      {
        id: "hs-boost",
        name: "Hesi Boost",
        role: "Stim flo",
        unit: "ml",
        about: "2 ml/L par à-coups, comme en coco.",
        comments: [{ tone: "note", text: "Le duo Floraison + Phosphor Plus fait déjà le gros. Boost = luxe." }],
        doses: [0, 0, 2, 0, 0, 2, 2, 2, 0, 0, 0],
      },
    ],
  },
  {
    id: "hesi-hydro",
    brand: "Hesi",
    name: "Hydro",
    medium: "hydro recirculé · laine",
    summary:
      "Hydro Growth puis Hydro Bloom, 5 ml/L en palier. PK 13/14 en rampe coco. Reservoir : EC qui monte = rajoute de l'eau, pas de l'engrais.",
    mixOrder: "Eau → Growth ou Bloom → Root → PowerZyme → PK. pH 5.5–6.0. Changer le bac tous les 7–10 jours.",
    source: "Hesi Hydro schedule (ml/10 L → ml/L)",
    weeks: VEG2_FLOWER8_FLUSH.map((w, i) => ({
      ...w,
      ph: "5.5–6.0",
      ec: i === 10 ? "flush" : i < 2 ? "1.0–1.4" : "1.4–2.0",
    })),
    products: [
      {
        id: "hh-g",
        name: "Hydro Growth",
        role: "Base veg",
        unit: "ml",
        about: "5 ml/L en veg hydro. Moins d'organique que TNT, plus stable en bac.",
        comments: [{ tone: "plus", text: "Tient le pH mieux que TNT dans un réservoir." }],
        doses: [2.5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      },
      {
        id: "hh-b",
        name: "Hydro Bloom",
        role: "Base flo",
        unit: "ml",
        about: "5 ml/L toute la flo.",
        comments: [{ tone: "moins", text: "En DWC chaude, 5 ml/L + PK = EC qui dérive. 70 % et on lit le truncheon." }],
        doses: [0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 0],
      },
      {
        id: "hh-root",
        name: "Root Complex",
        role: "Racines",
        unit: "ml",
        about: "2 ml/L en début de run.",
        comments: [{ tone: "note", text: "En NFT/DWC, certains le trouvent collant. Dose courte, puis stop." }],
        doses: [2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0],
      },
      {
        id: "hh-pk",
        name: "PK 13/14",
        role: "Booster flo",
        unit: "ml",
        about: "Même rampe que le coco : 0.25 → 1.5 ml/L.",
        comments: [{ tone: "moins", text: "En recirculé, le PK s'accumule. Rampe plus plate que le tableau papier." }],
        doses: [0, 0, 0, 0, 0, 0.25, 0.5, 0.75, 1.5, 0, 0],
      },
      {
        id: "hh-zym",
        name: "PowerZyme",
        role: "Enzymes",
        unit: "ml",
        about: "2 ml/L. Utile pour les racines dans l'eau.",
        comments: [{ tone: "plus", text: "En hydro, les enzymes valent plus qu'en terre." }],
        doses: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
      },
    ],
  },
  {
    id: "atami-coco",
    brand: "Atami",
    name: "B'cuzz Coco A+B",
    medium: "coco",
    summary:
      "A+B toute la run, Bloombastic dès le début de flo. Doses au milieu des fourchettes officielles (ml/L). Bloombastic est épais — seringue, pas bouchon.",
    mixOrder: "Eau → A → B → CalMag → Root stim → Atazyme → Bloombastic en dernier. Jamais A+B concentrés. pH 5.5–6.0.",
    source: "Atami B'cuzz Coco grow guide (ml/L, milieu de fourchette)",
    weeks: [
      { id: "g1", label: "Veg 1", phase: "veg", ec: "1.2–1.6", ph: "5.5–6.0" },
      { id: "g2", label: "Veg 2", phase: "veg", ec: "1.4–1.8", ph: "5.5–6.0" },
      { id: "g3", label: "Veg 3", phase: "veg", ec: "1.6–2.0", ph: "5.5–6.0" },
      { id: "f1", label: "Flo 1", phase: "flower", ec: "1.8–2.2", ph: "5.5–6.0" },
      { id: "f2", label: "Flo 2", phase: "flower", ec: "1.8–2.4", ph: "5.5–6.0" },
      { id: "f3", label: "Flo 3", phase: "flower", ec: "1.8–2.4", ph: "5.5–6.0" },
      { id: "f4", label: "Flo 4", phase: "flower", ec: "1.8–2.4", ph: "5.5–6.0" },
      { id: "f5", label: "Flo 5", phase: "flower", ec: "1.6–2.2", ph: "5.5–6.0" },
      { id: "f6", label: "Flo 6", phase: "flower", ec: "1.4–2.0", ph: "5.8–6.2" },
      { id: "fl", label: "Flush", phase: "flush", ec: "eau", ph: "6.0" },
    ],
    products: [
      {
        id: "ata-a",
        name: "Coco A",
        role: "Base",
        unit: "ml",
        npk: "NK 5-5",
        about: "Calcium + nitrates. 1.5 → 2.9 ml/L. Toujours égal à B.",
        mixTip: "En premier.",
        comments: [
          { tone: "plus", text: "Coco A est dosé Ca : moins de carences sous LED qu'un A+B générique." },
          { tone: "note", text: "Fourchette officielle 1–3.4 ml/L. Ici le milieu — monte si l'EC d'eau est basse." },
        ],
        doses: [1.5, 2, 2.5, 2.9, 2.8, 2.7, 2.6, 2.5, 2.5, 0],
      },
      {
        id: "ata-b",
        name: "Coco B",
        role: "Base",
        unit: "ml",
        npk: "PK 4-6",
        about: "P, K, micros. Égal à A.",
        comments: [{ tone: "moins", text: "Mélanger A et B purs : précipité. Toujours l'eau d'abord." }],
        doses: [1.5, 2, 2.5, 2.9, 2.8, 2.7, 2.6, 2.5, 2.5, 0],
      },
      {
        id: "ata-bb",
        name: "Bloombastic",
        role: "Booster flo",
        unit: "ml",
        about: "0.5 puis ~0.9 ml/L. PK + bio-stimulateurs. Le plus commenté d'Atami.",
        mixTip: "Épais. Seringue. En dernier dans le mélange.",
        comments: [
          { tone: "plus", text: "« Une bouteille qui se voit » — densité, brillance. Refrain très fréquent." },
          { tone: "moins", text: "À 1.2 ml/L + A/B au max, l'EC s'envole. 0.6–0.8 suffit souvent. Prix au ml." },
        ],
        doses: [0, 0, 0, 0.5, 0.9, 0.9, 0.9, 0.9, 0.9, 0],
      },
      {
        id: "ata-root",
        name: "Root Stimulator",
        role: "Racines",
        unit: "ml",
        about: "0.5–1 ml/L en veg. Rootbastic (0.1 ml/L) est encore plus concentré — ici le Stimulator classique.",
        comments: [{ tone: "note", text: "Rootbastic à 0.1 ml/L : une pipette. Ne pas le confondre avec celui-ci." }],
        doses: [1, 0.8, 0.5, 0, 0, 0, 0, 0, 0, 0],
      },
      {
        id: "ata-zym",
        name: "Atazyme",
        role: "Enzymes",
        unit: "ml",
        about: "1 ml/L presque toute la run.",
        comments: [{ tone: "plus", text: "Propre, pas cher dans la gamme. Peu de gens s'en plaignent." }],
        doses: [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
      },
      {
        id: "ata-cal",
        name: "ATA CalMag",
        role: "Cal-mag",
        unit: "ml",
        about: "0.15–0.45 ml/L. En eau douce / osmose, plutôt le haut.",
        comments: [{ tone: "note", text: "Coco A porte déjà du Ca. CalMag surtout si osmose ou LED très forte." }],
        doses: [0.45, 0.4, 0.3, 0.3, 0.2, 0.2, 0.15, 0.15, 0.15, 0],
      },
    ],
  },
  {
    id: "plagron-coco",
    brand: "Plagron",
    name: "100% Coco",
    medium: "coco",
    summary:
      "Cocos A+B, doses officielles par 10 L. Green Sensation à 1 ml/L dès flo 4. EC 2.5 en palier — c'est un schéma musclé, 70 % est légitime en tente.",
    mixOrder: "Eau → Cocos A → B → Power Roots / Pure Zym → Green Sensation / Sugar Royal. pH 5.5–6.5. Chaque arrosage, 10–20 % de runoff.",
    source: "Plagron 100% Coco (ml/10 L → ml/L, PL-23-083)",
    weeks: VEG2_FLOWER8_FLUSH.map((w, i) => ({
      ...w,
      ph: "5.5–6.5",
      ec: i === 10 ? "eau" : ["1.3", "1.5", "1.7", "1.9", "2.1", "2.5", "2.5", "2.5", "2.5", "2.5", "eau"][i],
    })),
    products: [
      {
        id: "pc-a",
        name: "Cocos A",
        role: "Base",
        unit: "ml",
        about: "1.5 → 3.5 ml/L (15–35 ml/10 L). Égal à B.",
        mixTip: "A puis B, jamais l'inverse mélangés purs.",
        comments: [
          { tone: "plus", text: "Le 100% Coco Plagron est un standard EU. Recette lisible, A=B." },
          { tone: "moins", text: "3.5 ml/L + Green Sensation : EC 2.5. En 60×60, beaucoup restent à 2.5 ml/L." },
        ],
        doses: [1.5, 2, 2.5, 3, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 0],
      },
      {
        id: "pc-b",
        name: "Cocos B",
        role: "Base",
        unit: "ml",
        about: "Égal à A.",
        comments: [{ tone: "note", text: "Si tu coupes A, tu coupes B d'autant." }],
        doses: [1.5, 2, 2.5, 3, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 0],
      },
      {
        id: "pc-roots",
        name: "Power Roots",
        role: "Racines",
        unit: "ml",
        about: "1 ml/L les 5 premières semaines.",
        comments: [{ tone: "plus", text: "Discret, régulier. Rarement incriminé dans un lockout." }],
        doses: [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
      },
      {
        id: "pc-zym",
        name: "Pure Zym",
        role: "Enzymes",
        unit: "ml",
        about: "1 ml/L jusqu'en mi-flo.",
        comments: [{ tone: "note", text: "Confort de coco plus que booster de têtes." }],
        doses: [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
      },
      {
        id: "pc-gs",
        name: "Green Sensation",
        role: "Booster flo",
        unit: "ml",
        about: "1 ml/L (10 ml/10 L) à partir de flo 4. Le plus commenté de Plagron.",
        comments: [
          { tone: "plus", text: "Densité et brillance — « ça vaut la bouteille » revient tout le temps." },
          { tone: "moins", text: "Prix. Beaucoup gardent GS et sautent Sugar Royal + Power Buds." },
        ],
        doses: [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0],
      },
      {
        id: "pc-sugar",
        name: "Sugar Royal",
        role: "Glucides",
        unit: "ml",
        about: "1 ml/L presque toute la run.",
        comments: [{ tone: "note", text: "Moins décisif que Green Sensation d'après la plupart des retours." }],
        doses: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
      },
      {
        id: "pc-buds",
        name: "Power Buds",
        role: "Pré-flo",
        unit: "ml",
        about: "1 ml/L dès flo 1. Transition stretch → têtes.",
        comments: [{ tone: "note", text: "Optionnel si Green Sensation est déjà là. Stack complet = EC trop vite." }],
        doses: [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
      },
    ],
  },
  {
    id: "plagron-hydro",
    brand: "Plagron",
    name: "100% Hydro",
    medium: "hydro · billes · laine",
    summary:
      "Hydro A+B, doses officielles plus basses que le coco (10–16 ml/10 L). Green Sensation en deuxième moitié. pH 5.5.",
    mixOrder: "Eau → Hydro A → B → Power Roots → Green Sensation. A=B. pH 5.5. EC max < 3.",
    source: "Plagron 100% Hydro (ml/10 L → ml/L)",
    weeks: VEG2_FLOWER8_FLUSH.map((w, i) => ({
      ...w,
      ph: "5.5",
      ec: i === 10 ? "eau" : i < 2 ? "1.4" : i < 5 ? "1.5–1.9" : "2.2",
    })),
    products: [
      {
        id: "ph-a",
        name: "Hydro A",
        role: "Base",
        unit: "ml",
        npk: "3-0-1",
        about: "1.0 → 1.6 ml/L. Moins concentré en ml que Cocos A — la formule est autre.",
        comments: [{ tone: "plus", text: "Bac stable, A=B, pas d'histoire. Le schéma hydro le plus lu en EU avec Canna Aqua." }],
        doses: [1, 1, 1.2, 1.4, 1.6, 1.6, 1.6, 1.6, 1.6, 1.6, 0],
      },
      {
        id: "ph-b",
        name: "Hydro B",
        role: "Base",
        unit: "ml",
        npk: "1-3-6",
        about: "Égal à A.",
        comments: [{ tone: "moins", text: "Mélanger A et B purs = cristaux. Toujours l'eau d'abord." }],
        doses: [1, 1, 1.2, 1.4, 1.6, 1.6, 1.6, 1.6, 1.6, 1.6, 0],
      },
      {
        id: "ph-roots",
        name: "Power Roots",
        role: "Racines",
        unit: "ml",
        about: "1 ml/L, 5 premières semaines.",
        comments: [{ tone: "note", text: "En DWC, courte fenêtre puis stop — les gels organiques alourdissent le bac." }],
        doses: [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
      },
      {
        id: "ph-zym",
        name: "Pure Zym",
        role: "Enzymes",
        unit: "ml",
        about: "1 ml/L en début de run.",
        comments: [{ tone: "plus", text: "En recirculé, les enzymes aident plus qu'en terreau." }],
        doses: [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
      },
      {
        id: "ph-gs",
        name: "Green Sensation",
        role: "Booster flo",
        unit: "ml",
        about: "1 ml/L à partir de flo 4.",
        comments: [{ tone: "plus", text: "Même bouteille que le schéma Terra/Coco — un achat, trois milieux." }],
        doses: [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0],
      },
    ],
  },
  {
    id: "canna-aqua",
    brand: "Canna",
    name: "Aqua Vega / Flores",
    medium: "hydro recirculé",
    summary:
      "Pour bacs et goutte-à-goutte recirculés. Vega A+B en veg, Flores A+B en flo. Doses au milieu des fourchettes officielles (ml/10 L). Surveille l'EC du bac : s'il monte, tu rajoutes de l'eau.",
    mixOrder: "Eau → Vega ou Flores A → B → Rhizotonic → Cannazym → Boost → PK une semaine. pH 5.2–6.2. Bac 7–14 j.",
    source: "CANNA Aqua schedule (ml/10 L → ml/L)",
    weeks: [
      { id: "g1", label: "Racine", phase: "veg", ec: "1.1–1.5", ph: "5.2–6.2" },
      { id: "g2", label: "Veg I", phase: "veg", ec: "1.3–1.7", ph: "5.2–6.2" },
      { id: "g3", label: "Veg II", phase: "veg", ec: "1.6–2.0", ph: "5.2–6.2" },
      { id: "f1", label: "Flo I", phase: "flower", ec: "1.8–2.2", ph: "5.5–6.2" },
      { id: "f2", label: "Flo I+", phase: "flower", ec: "1.8–2.2", ph: "5.5–6.2" },
      { id: "f3", label: "PK", phase: "flower", ec: "2.0–2.4", ph: "5.5–6.2" },
      { id: "f4", label: "Flo III", phase: "flower", ec: "1.4–1.8", ph: "5.5–6.2" },
      { id: "f5", label: "Flo III+", phase: "flower", ec: "1.4–1.8", ph: "5.5–6.2" },
      { id: "f6", label: "Mûr", phase: "flower", ec: "1.2–1.6", ph: "5.8–6.2" },
      { id: "fl", label: "Flush", phase: "flush", ec: "0.4", ph: "5.8–6.2" },
    ],
    products: [
      {
        id: "ca-va",
        name: "Aqua Vega A",
        role: "Base veg",
        unit: "ml",
        about: "2.5–3.2 ml/L. Toujours égal à B. On coupe à l'entrée en Flores.",
        comments: [{ tone: "plus", text: "Conçu pour recirculer : moins de dérive pH que beaucoup d'A+B « drain »." }],
        doses: [2.5, 2.8, 3.2, 0, 0, 0, 0, 0, 0, 0],
      },
      {
        id: "ca-vb",
        name: "Aqua Vega B",
        role: "Base veg",
        unit: "ml",
        about: "Égal à Vega A.",
        comments: [{ tone: "note", text: "Ne pas garder Vega en 12/12 : trop d'azote, stretch + tard." }],
        doses: [2.5, 2.8, 3.2, 0, 0, 0, 0, 0, 0, 0],
      },
      {
        id: "ca-fa",
        name: "Aqua Flores A",
        role: "Base flo",
        unit: "ml",
        about: "3.4 ml/L en pic, on redescend en fin.",
        comments: [{ tone: "moins", text: "EC bac qui grimpe = les plantes boivent plus vite que les sels. Eau claire, pas plus d'engrais." }],
        doses: [0, 0, 0, 3.4, 3.4, 3.4, 3, 3, 2, 0],
      },
      {
        id: "ca-fb",
        name: "Aqua Flores B",
        role: "Base flo",
        unit: "ml",
        about: "Égal à Flores A.",
        comments: [{ tone: "note", text: "A et B toujours jumelés, même en fade." }],
        doses: [0, 0, 0, 3.4, 3.4, 3.4, 3, 3, 2, 0],
      },
      {
        id: "ca-rhizo",
        name: "Rhizotonic",
        role: "Racines",
        unit: "ml",
        about: "4 ml/L en racine, puis 2, puis 0.5.",
        comments: [{ tone: "plus", text: "Même bouteille que Coco/Terra. Un additif, trois schémas Canna." }],
        doses: [4, 2, 2, 0.5, 0.5, 0.5, 0.5, 0, 0, 0],
      },
      {
        id: "ca-zym",
        name: "Cannazym",
        role: "Enzymes",
        unit: "ml",
        about: "2.5 ml/L, 3.5 en fin / flush.",
        comments: [{ tone: "plus", text: "En hydro, garder les racines mortes hors du bac change vraiment la donne." }],
        doses: [0, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 3.5, 3.5],
      },
      {
        id: "ca-boost",
        name: "Cannaboost",
        role: "Stim flo",
        unit: "ml",
        about: "2–3 ml/L en flo.",
        comments: [{ tone: "note", text: "Même débat que sur Coco : A+B font 80 %, Boost est un luxe." }],
        doses: [0, 0, 2, 3, 3, 3, 3, 3, 2, 0],
      },
      {
        id: "ca-pk",
        name: "PK 13/14",
        role: "Booster 1 semaine",
        unit: "ml",
        about: "1.5 ml/L, une semaine, 3–4 semaines avant récolte.",
        comments: [{ tone: "moins", text: "En recirculé, une semaine veut dire un bac. Pas trois." }],
        doses: [0, 0, 0, 0, 0, 1.5, 0, 0, 0, 0],
      },
    ],
  },
  {
    id: "mills-basis",
    brand: "Mills",
    name: "Basis A+B",
    medium: "coco · hydro · terre",
    summary:
      "Base hollandaise propre. Start-R en veg, C4 en flo, Ultimate PK en mi-flo. Doses modestes en ml/L — ne pas juger au volume, la formule est concentrée.",
    mixOrder: "Eau → Basis A → B → Start-R / C4 → Vitalize → Ultimate PK. pH 5.8–6.2 coco, 6.0–6.5 terre.",
    source: "Mills Basis quick schedule (ml/L)",
    weeks: [
      { id: "g1", label: "Plantule", phase: "veg", ec: "0.6–1.0", ph: "5.8–6.2" },
      { id: "g2", label: "Veg", phase: "veg", ec: "1.2–1.6", ph: "5.8–6.2" },
      { id: "g3", label: "Veg+", phase: "veg", ec: "1.4–1.8", ph: "5.8–6.2" },
      { id: "f1", label: "Flo 1", phase: "flower", ec: "1.6–2.0", ph: "5.8–6.2" },
      { id: "f2", label: "Flo 2", phase: "flower", ec: "1.6–2.0", ph: "5.8–6.2" },
      { id: "f3", label: "Flo 3", phase: "flower", ec: "1.8–2.2", ph: "5.8–6.2" },
      { id: "f4", label: "Flo 4", phase: "flower", ec: "1.8–2.2", ph: "5.8–6.2" },
      { id: "f5", label: "Flo 5", phase: "flower", ec: "1.4–1.8", ph: "5.8–6.2" },
      { id: "fl", label: "Flush", phase: "flush", ec: "eau", ph: "6.0" },
    ],
    products: [
      {
        id: "mi-a",
        name: "Basis A",
        role: "Base",
        unit: "ml",
        about: "0.5 → 2 ml/L. Toujours égal à B.",
        comments: [
          { tone: "plus", text: "Propre, peu d'odeur, pH calme. Les salles qui quittent AN pour Mills parlent de ça." },
          { tone: "moins", text: "Prix. Tu payes la concentration et l'étiquette hollandaise." },
        ],
        doses: [0.5, 1.5, 1.5, 2, 2, 2, 2, 1.5, 0],
      },
      {
        id: "mi-b",
        name: "Basis B",
        role: "Base",
        unit: "ml",
        about: "Égal à A.",
        comments: [{ tone: "note", text: "A=B. Si tu règlés à l'EC, tu bouges les deux." }],
        doses: [0.5, 1.5, 1.5, 2, 2, 2, 2, 1.5, 0],
      },
      {
        id: "mi-start",
        name: "Start-R",
        role: "Racines / veg",
        unit: "ml",
        about: "0.3–0.5 ml/L en veg. Extraits + enzymes, pas un NPK.",
        comments: [
          { tone: "plus", text: "Souvent le premier « waouh » Mills : reprise de bouture, poils blancs." },
          { tone: "note", text: "Inutile de le trainer en flo. C4 prend le relais." },
        ],
        doses: [0.3, 0.5, 0.5, 0, 0, 0, 0, 0, 0],
      },
      {
        id: "mi-c4",
        name: "C4",
        role: "Booster flo",
        unit: "ml",
        about: "0.5 puis 1 ml/L en flo. PK + bio.",
        comments: [{ tone: "plus", text: "Le booster dont on parle après Start-R. 1 ml/L, pas 4." }],
        doses: [0, 0, 0, 0.5, 0.5, 1, 1, 0, 0],
      },
      {
        id: "mi-vit",
        name: "Vitalize",
        role: "Silice",
        unit: "ml",
        about: "0.3–0.5 ml/L. Silicium — tiges, stress lumineux. En premier dans l'eau, avant A.",
        mixTip: "Vitalize d'abord, seul, mélanger, puis A.",
        comments: [{ tone: "plus", text: "Sous LED, la silice se défend. Ceux qui l'enlèvent voient parfois plus de molles." }],
        doses: [0, 0.3, 0.3, 0.5, 0.5, 0, 0, 0, 0],
      },
      {
        id: "mi-pk",
        name: "Ultimate PK",
        role: "PK flo",
        unit: "ml",
        about: "0.3–0.5 ml/L en mi/fin de flo. Ne pas stacker avec C4 au max trop longtemps.",
        comments: [{ tone: "moins", text: "C4 + Ultimate PK + Basis 2 ml/L : surveille le runoff. Un des deux boosters suffit souvent." }],
        doses: [0, 0, 0, 0, 0.5, 0.5, 0.3, 0.3, 0],
      },
    ],
  },
  {
    id: "foxfarm-trio",
    brand: "Fox Farm",
    name: "Trio (Grow · Tiger · Big Bloom)",
    medium: "terreau",
    summary:
      "Schéma US converti (c. à café / gallon → ml/L). Big Bloom presque toute la run, Grow Big en veg, Tiger Bloom en flo. Un arrosage sur deux en terreau chargé (Ocean Forest).",
    mixOrder: "Eau → Big Bloom → Grow Big ou Tiger Bloom. pH 6.3–6.8 terre. Ocean Forest : 2–3 semaines d'eau claire d'abord.",
    source: "FoxFarm soil trio (tsp/gal → ml/L, 1 tsp/gal ≈ 1.3 ml/L)",
    weeks: VEG2_FLOWER8_FLUSH.map((w, i) => ({
      ...w,
      ph: "6.3–6.8",
      ec: i === 10 ? "eau" : i < 2 ? "0.8–1.2" : "1.2–1.8",
    })),
    products: [
      {
        id: "ff-grow",
        name: "Grow Big",
        role: "Base veg",
        unit: "ml",
        npk: "6-4-4",
        about: "≈ 1.3–2.6 ml/L (1–2 tsp/gal) en veg. On le coupe en flo.",
        comments: [
          { tone: "plus", text: "Le trio est une porte d'entrée US : trois bouteilles, un geste." },
          { tone: "moins", text: "Ocean Forest + Grow Big dès J1 = burn. Le sac est déjà un engrais." },
        ],
        doses: [1.3, 2.6, 2.6, 1.3, 0, 0, 0, 0, 0, 0, 0],
      },
      {
        id: "ff-tiger",
        name: "Tiger Bloom",
        role: "Base flo",
        unit: "ml",
        npk: "2-8-4",
        about: "≈ 2.6–4 ml/L en flo (2–3 tsp/gal).",
        comments: [{ tone: "note", text: "Forte odeur, formule minérale. Les pointes parlent vite si tu doubles avec Big Bloom au max." }],
        doses: [0, 0, 2.6, 4, 4, 4, 4, 2.6, 1.3, 0, 0],
      },
      {
        id: "ff-big",
        name: "Big Bloom",
        role: "Organique / flo",
        unit: "ml",
        npk: "0.01-0.3-0.7",
        about: "≈ 8 ml/L (6 tsp/gal). Guano + vers, très dilué en NPK — le volume n'est pas un 8 ml/L de base minérale.",
        comments: [
          { tone: "plus", text: "Beaucoup le gardent même en changeant de base. Nez, sol vivant, peu de burn à lui seul." },
          { tone: "note", text: "Ça sent le poisson/guano. Secoue fort, filtre si goutte-à-goutte." },
        ],
        doses: [8, 8, 8, 8, 8, 8, 8, 8, 8, 4, 0],
      },
    ],
  },
  {
    id: "hg-aqua",
    brand: "House & Garden",
    name: "Aqua Flakes A+B",
    medium: "hydro recirculé · laine · billes",
    summary:
      "A+B 1–2.5 ml/L. Roots Excelurator en veg (très concentré). Bud XL en flo. Schéma de salle — 70 % si tes LED sont déjà hautes.",
    mixOrder: "Eau → A → B → Roots Excelurator → Bud XL. A=B. pH 5.5–6.2. Bac propre, 7–10 j.",
    source: "H&G Aqua Flakes (ml/L, synthèse tableau 8–10 sem.)",
    weeks: VEG2_FLOWER8_FLUSH.map((w, i) => ({
      ...w,
      ph: "5.5–6.2",
      ec: i === 10 ? "flush" : i < 2 ? "1.2–1.6" : "1.6–2.2",
    })),
    products: [
      {
        id: "hg-a",
        name: "Aqua Flakes A",
        role: "Base",
        unit: "ml",
        npk: "3-0-2",
        about: "1 → 2.5 ml/L. Égal à B. Conçu pour recirculer (pompes, aimants).",
        comments: [
          { tone: "plus", text: "pH calme en bac. C'est pour ça que les DWC l'ont adopté." },
          { tone: "note", text: "Il existe Cocos A+B et Soil A+B — ne pas coller Aqua Flakes en terreau." },
        ],
        doses: [1, 1.5, 2, 2.2, 2.5, 2.5, 2.5, 2.2, 2, 1.5, 0],
      },
      {
        id: "hg-b",
        name: "Aqua Flakes B",
        role: "Base",
        unit: "ml",
        npk: "1-3-5",
        about: "Égal à A.",
        comments: [{ tone: "moins", text: "A et B purs ensemble : précipité. Comme tout A+B." }],
        doses: [1, 1.5, 2, 2.2, 2.5, 2.5, 2.5, 2.2, 2, 1.5, 0],
      },
      {
        id: "hg-root",
        name: "Roots Excelurator",
        role: "Racines",
        unit: "ml",
        about: "0.3 ml/L en veg, 0.15 en entrée de flo. Une des bouteilles les plus chères du rayon.",
        comments: [
          { tone: "plus", text: "Racines blanches, reprise — le mythe a une base. Ceux qui l'ont goûté en bouture en parlent encore." },
          { tone: "moins", text: "Le ml le plus cher du marché. 50 % de la dose officielle suffit souvent. Ne pas le verser au bouchon." },
        ],
        doses: [0.3, 0.3, 0.3, 0.15, 0, 0, 0, 0, 0, 0, 0],
      },
      {
        id: "hg-xl",
        name: "Bud XL",
        role: "Booster flo",
        unit: "ml",
        about: "1 ml/L en flo, pour la densité et les calices.",
        comments: [{ tone: "plus", text: "Plus discret que Bloombastic, moins de « syrup ». Beaucoup le gardent sans stack PK." }],
        doses: [0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0],
      },
      {
        id: "hg-zen",
        name: "Multi Zen",
        role: "Enzymes / bac",
        unit: "ml",
        about: "0.2 ml/L. Enzymes + nettoyage de ligne, utile en recirculé.",
        comments: [{ tone: "note", text: "Surtout pour le bac. En arrosoir coco, optionnel." }],
        doses: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0],
      },
    ],
  },
];

export function programById(id: string) {
  return PROGRAMS.find((p) => p.id === id) ?? PROGRAMS[0];
}

export function programsForBrand(brand: string) {
  return PROGRAMS.filter((p) => p.brand === brand);
}

export function doseFor(product: FeedProduct, weekIndex: number) {
  return product.doses[weekIndex] ?? 0;
}

export function litersTotal(perLiter: number, liters: number, strength = 1) {
  return perLiter * liters * strength;
}

export const STRENGTHS = [
  { id: 0.5, label: "50 %" },
  { id: 0.7, label: "70 %" },
  { id: 1, label: "100 %" },
] as const;

export const BRANDS = [...new Set(PROGRAMS.map((p) => p.brand))];
